{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "llm-slo-agent.serviceAccountName" . }}
  namespace: {{ include "llm-slo-agent.namespace" . }}
  labels:
    {{- include "llm-slo-agent.labels" . | nindent 4 }}
{{- end }}
